/* !---- DO NOT EDIT: This file autogenerated by com/jogamp/gluegen/opengl/GLEmitter.java on Sat Oct 10 03:20:16 CEST 2015 ----! */


package jogamp.opengl.windows.wgl;

import java.nio.*;

import com.jogamp.gluegen.runtime.*;
import com.jogamp.common.os.*;
import com.jogamp.common.nio.*;
import jogamp.common.os.MachineDataInfoRuntime;

import java.util.*;
import com.jogamp.opengl.*;
import com.jogamp.opengl.fixedfunc.*;
import jogamp.opengl.*;

public class RECT {

  StructAccessor accessor;

  private static final int mdIdx = MachineDataInfoRuntime.getStatic().ordinal();
  private final MachineDataInfo md;

  private static final int[] RECT_size = new int[] { 16 /* ARM_MIPS_32 */, 16 /* X86_32_UNIX */, 16 /* X86_32_MACOS */, 16 /* PPC_32_UNIX */, 16 /* SPARC_32_SUNOS */, 16 /* X86_32_WINDOWS */, 16 /* LP64_UNIX */, 16 /* X86_64_WINDOWS */  };
  private static final int[] left_offset = new int[] { 0 /* ARM_MIPS_32 */, 0 /* X86_32_UNIX */, 0 /* X86_32_MACOS */, 0 /* PPC_32_UNIX */, 0 /* SPARC_32_SUNOS */, 0 /* X86_32_WINDOWS */, 0 /* LP64_UNIX */, 0 /* X86_64_WINDOWS */ };
//private static final int[] left_size = new int[] { 4 /* ARM_MIPS_32 */, 4 /* X86_32_UNIX */, 4 /* X86_32_MACOS */, 4 /* PPC_32_UNIX */, 4 /* SPARC_32_SUNOS */, 4 /* X86_32_WINDOWS */, 4 /* LP64_UNIX */, 4 /* X86_64_WINDOWS */  };
  private static final int[] top_offset = new int[] { 4 /* ARM_MIPS_32 */, 4 /* X86_32_UNIX */, 4 /* X86_32_MACOS */, 4 /* PPC_32_UNIX */, 4 /* SPARC_32_SUNOS */, 4 /* X86_32_WINDOWS */, 4 /* LP64_UNIX */, 4 /* X86_64_WINDOWS */ };
//private static final int[] top_size = new int[] { 4 /* ARM_MIPS_32 */, 4 /* X86_32_UNIX */, 4 /* X86_32_MACOS */, 4 /* PPC_32_UNIX */, 4 /* SPARC_32_SUNOS */, 4 /* X86_32_WINDOWS */, 4 /* LP64_UNIX */, 4 /* X86_64_WINDOWS */  };
  private static final int[] right_offset = new int[] { 8 /* ARM_MIPS_32 */, 8 /* X86_32_UNIX */, 8 /* X86_32_MACOS */, 8 /* PPC_32_UNIX */, 8 /* SPARC_32_SUNOS */, 8 /* X86_32_WINDOWS */, 8 /* LP64_UNIX */, 8 /* X86_64_WINDOWS */ };
//private static final int[] right_size = new int[] { 4 /* ARM_MIPS_32 */, 4 /* X86_32_UNIX */, 4 /* X86_32_MACOS */, 4 /* PPC_32_UNIX */, 4 /* SPARC_32_SUNOS */, 4 /* X86_32_WINDOWS */, 4 /* LP64_UNIX */, 4 /* X86_64_WINDOWS */  };
  private static final int[] bottom_offset = new int[] { 12 /* ARM_MIPS_32 */, 12 /* X86_32_UNIX */, 12 /* X86_32_MACOS */, 12 /* PPC_32_UNIX */, 12 /* SPARC_32_SUNOS */, 12 /* X86_32_WINDOWS */, 12 /* LP64_UNIX */, 12 /* X86_64_WINDOWS */ };
//private static final int[] bottom_size = new int[] { 4 /* ARM_MIPS_32 */, 4 /* X86_32_UNIX */, 4 /* X86_32_MACOS */, 4 /* PPC_32_UNIX */, 4 /* SPARC_32_SUNOS */, 4 /* X86_32_WINDOWS */, 4 /* LP64_UNIX */, 4 /* X86_64_WINDOWS */  };

  public static int size() {
    return RECT_size[mdIdx];
  }

  public static RECT create() {
    return create(Buffers.newDirectByteBuffer(size()));
  }

  public static RECT create(java.nio.ByteBuffer buf) {
      return new RECT(buf);
  }

  RECT(java.nio.ByteBuffer buf) {
    md = MachineDataInfo.StaticConfig.values()[mdIdx].md;
    accessor = new StructAccessor(buf);
  }

  public java.nio.ByteBuffer getBuffer() {
    return accessor.getBuffer();
  }

  /** Setter for native field <code>left</code>: CType[(IntType) typedef 'LONG', size [fixed true, lnx64 4], [const[false], int]] */
  public RECT setLeft(int val) {
    accessor.setIntAt(left_offset[mdIdx], val);
    return this;
  }

  /** Getter for native field <code>left</code>: CType[(IntType) typedef 'LONG', size [fixed true, lnx64 4], [const[false], int]] */
  public int getLeft() {
    return accessor.getIntAt(left_offset[mdIdx]);
  }

  /** Setter for native field <code>top</code>: CType[(IntType) typedef 'LONG', size [fixed true, lnx64 4], [const[false], int]] */
  public RECT setTop(int val) {
    accessor.setIntAt(top_offset[mdIdx], val);
    return this;
  }

  /** Getter for native field <code>top</code>: CType[(IntType) typedef 'LONG', size [fixed true, lnx64 4], [const[false], int]] */
  public int getTop() {
    return accessor.getIntAt(top_offset[mdIdx]);
  }

  /** Setter for native field <code>right</code>: CType[(IntType) typedef 'LONG', size [fixed true, lnx64 4], [const[false], int]] */
  public RECT setRight(int val) {
    accessor.setIntAt(right_offset[mdIdx], val);
    return this;
  }

  /** Getter for native field <code>right</code>: CType[(IntType) typedef 'LONG', size [fixed true, lnx64 4], [const[false], int]] */
  public int getRight() {
    return accessor.getIntAt(right_offset[mdIdx]);
  }

  /** Setter for native field <code>bottom</code>: CType[(IntType) typedef 'LONG', size [fixed true, lnx64 4], [const[false], int]] */
  public RECT setBottom(int val) {
    accessor.setIntAt(bottom_offset[mdIdx], val);
    return this;
  }

  /** Getter for native field <code>bottom</code>: CType[(IntType) typedef 'LONG', size [fixed true, lnx64 4], [const[false], int]] */
  public int getBottom() {
    return accessor.getIntAt(bottom_offset[mdIdx]);
  }
}
