/* !---- DO NOT EDIT: This file autogenerated by com/jogamp/gluegen/JavaEmitter.java on Sat Oct 10 03:10:34 CEST 2015 ----! */


package jogamp.nativewindow.windows;

import java.nio.*;

import com.jogamp.gluegen.runtime.*;
import com.jogamp.common.os.*;
import com.jogamp.common.nio.*;
import jogamp.common.os.MachineDataInfoRuntime;

import com.jogamp.nativewindow.util.Point;
import com.jogamp.nativewindow.NativeWindowException;
import jogamp.nativewindow.NWJNILibLoader;
import jogamp.nativewindow.Debug;

public class MARGINS {

  StructAccessor accessor;

  private static final int mdIdx = MachineDataInfoRuntime.getStatic().ordinal();
  private final MachineDataInfo md;

  private static final int[] MARGINS_size = new int[] { 16 /* ARM_MIPS_32 */, 16 /* X86_32_UNIX */, 16 /* X86_32_MACOS */, 16 /* PPC_32_UNIX */, 16 /* SPARC_32_SUNOS */, 16 /* X86_32_WINDOWS */, 16 /* LP64_UNIX */, 16 /* X86_64_WINDOWS */  };
  private static final int[] cxLeftWidth_offset = new int[] { 0 /* ARM_MIPS_32 */, 0 /* X86_32_UNIX */, 0 /* X86_32_MACOS */, 0 /* PPC_32_UNIX */, 0 /* SPARC_32_SUNOS */, 0 /* X86_32_WINDOWS */, 0 /* LP64_UNIX */, 0 /* X86_64_WINDOWS */ };
//private static final int[] cxLeftWidth_size = new int[] { 4 /* ARM_MIPS_32 */, 4 /* X86_32_UNIX */, 4 /* X86_32_MACOS */, 4 /* PPC_32_UNIX */, 4 /* SPARC_32_SUNOS */, 4 /* X86_32_WINDOWS */, 4 /* LP64_UNIX */, 4 /* X86_64_WINDOWS */  };
  private static final int[] cxRightWidth_offset = new int[] { 4 /* ARM_MIPS_32 */, 4 /* X86_32_UNIX */, 4 /* X86_32_MACOS */, 4 /* PPC_32_UNIX */, 4 /* SPARC_32_SUNOS */, 4 /* X86_32_WINDOWS */, 4 /* LP64_UNIX */, 4 /* X86_64_WINDOWS */ };
//private static final int[] cxRightWidth_size = new int[] { 4 /* ARM_MIPS_32 */, 4 /* X86_32_UNIX */, 4 /* X86_32_MACOS */, 4 /* PPC_32_UNIX */, 4 /* SPARC_32_SUNOS */, 4 /* X86_32_WINDOWS */, 4 /* LP64_UNIX */, 4 /* X86_64_WINDOWS */  };
  private static final int[] cyTopHeight_offset = new int[] { 8 /* ARM_MIPS_32 */, 8 /* X86_32_UNIX */, 8 /* X86_32_MACOS */, 8 /* PPC_32_UNIX */, 8 /* SPARC_32_SUNOS */, 8 /* X86_32_WINDOWS */, 8 /* LP64_UNIX */, 8 /* X86_64_WINDOWS */ };
//private static final int[] cyTopHeight_size = new int[] { 4 /* ARM_MIPS_32 */, 4 /* X86_32_UNIX */, 4 /* X86_32_MACOS */, 4 /* PPC_32_UNIX */, 4 /* SPARC_32_SUNOS */, 4 /* X86_32_WINDOWS */, 4 /* LP64_UNIX */, 4 /* X86_64_WINDOWS */  };
  private static final int[] cyBottomHeight_offset = new int[] { 12 /* ARM_MIPS_32 */, 12 /* X86_32_UNIX */, 12 /* X86_32_MACOS */, 12 /* PPC_32_UNIX */, 12 /* SPARC_32_SUNOS */, 12 /* X86_32_WINDOWS */, 12 /* LP64_UNIX */, 12 /* X86_64_WINDOWS */ };
//private static final int[] cyBottomHeight_size = new int[] { 4 /* ARM_MIPS_32 */, 4 /* X86_32_UNIX */, 4 /* X86_32_MACOS */, 4 /* PPC_32_UNIX */, 4 /* SPARC_32_SUNOS */, 4 /* X86_32_WINDOWS */, 4 /* LP64_UNIX */, 4 /* X86_64_WINDOWS */  };

  public static int size() {
    return MARGINS_size[mdIdx];
  }

  public static MARGINS create() {
    return create(Buffers.newDirectByteBuffer(size()));
  }

  public static MARGINS create(java.nio.ByteBuffer buf) {
      return new MARGINS(buf);
  }

  MARGINS(java.nio.ByteBuffer buf) {
    md = MachineDataInfo.StaticConfig.values()[mdIdx].md;
    accessor = new StructAccessor(buf);
  }

  public java.nio.ByteBuffer getBuffer() {
    return accessor.getBuffer();
  }

  /** Setter for native field <code>cxLeftWidth</code>: CType[(IntType) typedef 'int32_t', size [fixed true, lnx64 4], [const[false], int]] */
  public MARGINS setCxLeftWidth(int val) {
    accessor.setIntAt(cxLeftWidth_offset[mdIdx], val);
    return this;
  }

  /** Getter for native field <code>cxLeftWidth</code>: CType[(IntType) typedef 'int32_t', size [fixed true, lnx64 4], [const[false], int]] */
  public int getCxLeftWidth() {
    return accessor.getIntAt(cxLeftWidth_offset[mdIdx]);
  }

  /** Setter for native field <code>cxRightWidth</code>: CType[(IntType) typedef 'int32_t', size [fixed true, lnx64 4], [const[false], int]] */
  public MARGINS setCxRightWidth(int val) {
    accessor.setIntAt(cxRightWidth_offset[mdIdx], val);
    return this;
  }

  /** Getter for native field <code>cxRightWidth</code>: CType[(IntType) typedef 'int32_t', size [fixed true, lnx64 4], [const[false], int]] */
  public int getCxRightWidth() {
    return accessor.getIntAt(cxRightWidth_offset[mdIdx]);
  }

  /** Setter for native field <code>cyTopHeight</code>: CType[(IntType) typedef 'int32_t', size [fixed true, lnx64 4], [const[false], int]] */
  public MARGINS setCyTopHeight(int val) {
    accessor.setIntAt(cyTopHeight_offset[mdIdx], val);
    return this;
  }

  /** Getter for native field <code>cyTopHeight</code>: CType[(IntType) typedef 'int32_t', size [fixed true, lnx64 4], [const[false], int]] */
  public int getCyTopHeight() {
    return accessor.getIntAt(cyTopHeight_offset[mdIdx]);
  }

  /** Setter for native field <code>cyBottomHeight</code>: CType[(IntType) typedef 'int32_t', size [fixed true, lnx64 4], [const[false], int]] */
  public MARGINS setCyBottomHeight(int val) {
    accessor.setIntAt(cyBottomHeight_offset[mdIdx], val);
    return this;
  }

  /** Getter for native field <code>cyBottomHeight</code>: CType[(IntType) typedef 'int32_t', size [fixed true, lnx64 4], [const[false], int]] */
  public int getCyBottomHeight() {
    return accessor.getIntAt(cyBottomHeight_offset[mdIdx]);
  }
}
